#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091,SC2034

PLAN__PATH_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

while :; do
    case "$1" in
        -m | --modules)
            if [ ! -d "$2" ]; then
                printf '\033[31m[%-5s] %s\033[0m\n' \
                    'ERROR' "Invalid modules path '$2'"
                exit 1
            fi
            PLAN__PATH_MODULES="$2"
            shift
            ;;
        -c | --config)
            if [ ! -f "$2" ]; then
                printf '\033[31m[%-5s] %s\033[0m\n' \
                    'ERROR' "Invalid config path '$2'"
                exit 1
            fi
            PLAN__PATH_CONFIG="$2"
            shift
            ;;
        --)
            shift
            break
            ;;
        *) break ;;
    esac
    shift
done

#
# Core Config
#

source "${PLAN__PATH_ROOT}/planit.conf"
[ -n "$PLAN__PATH_CONFIG" ] \
    && source "$PLAN__PATH_CONFIG"
source "${PLAN__PATH_ROOT}/lib/utils.sh"

declare -a PLAN__PID_CACHE
declare -a PLAN__FILE_CACHE

trap 'Plan::utils.exit "$?" -p PLAN__PID_CACHE -f PLAN__FILE_CACHE' \
    INT TERM HUP QUIT EXIT

#
# Logging Setup
#

if [ -n "$PLAN__LOGGING_LOGS_DIR" ]; then
    mkdir -p "$PLAN__LOGGING_LOGS_DIR" || {
        printf '\033[31m[%-5s] %s\033[0m\n' \
            'ERROR' "Failed to create dir '$PLAN__LOGGING_LOGS_DIR'"
        exit 1
    }
    PLAN__PATH_LOG="$PLAN__LOGGING_LOGS_DIR"
else
    PLAN__PATH_LOG="$(mktemp -d)"
fi
[ "$PLAN__LOGGING_KEEP_LOGS" != 'true' ] \
    && PLAN__FILE_CACHE+=("$PLAN__PATH_LOG")
PLAN__PATH_LOG_OUT="${PLAN__PATH_LOG}/out.log"
PLAN__PATH_LOG_ERR="${PLAN__PATH_LOG}/err.log"
PLAN__PATH_LOG_ALL="${PLAN__PATH_LOG}/all.log"

PLAN__PATH_FIFO="${PLAN__PATH_LOG}/fifo"
PLAN__PATH_FIFO_OUT="${PLAN__PATH_FIFO}/out"
PLAN__PATH_FIFO_ERR="${PLAN__PATH_FIFO}/err"
PLAN__FILE_CACHE+=("$PLAN__PATH_FIFO")
{
    mkdir "$PLAN__PATH_FIFO" \
        && mkfifo "$PLAN__PATH_FIFO_OUT" \
        && mkfifo "$PLAN__PATH_FIFO_ERR"
} || {
    printf '\033[31m[%-5s] %s\033[0m\n' 'ERROR' 'Failed to created fifo'
    exit 1
}

#
# Run Modules
#

source "${PLAN__PATH_ROOT}/lib/monitor.sh"
source "${PLAN__PATH_ROOT}/lib/modules.sh"
tput civis # Cursor reset by error handler

declare -a PLAN__MODULES
Plan::modules.fetch PLAN__MODULES "$PLAN__PATH_MODULES" || exit 1

for ((i = 0; i < "${#PLAN__MODULES[@]}"; i++)); do
    module="${PLAN__MODULES[$i]}"

    # Listeners closed after each module call
    tee -a "$PLAN__PATH_LOG_ALL" > "$PLAN__PATH_LOG_OUT" < "$PLAN__PATH_FIFO_OUT" &
    PLAN__PID_CACHE+=("$!")
    tee -a "$PLAN__PATH_LOG_ALL" > "$PLAN__PATH_LOG_ERR" < "$PLAN__PATH_FIFO_ERR" &
    PLAN__PID_CACHE+=("$!")

    # Source in subshell to maintain clean environment in parent
    (
        config="$(Plan::modules.get_config "$module")" || exit 1

        [ -n "$config" ] \
            && { source "$config" || exit 1; }

        if [ -z "$PLAN__MODULE_TITLE" ]; then
            PLAN__MODULE_TITLE="$(Plan::modules.format_title "$module")"
            [ -z "$PLAN__MODULE_TITLE" ] \
                && PLAN__MODULE_TITLE="$PLAN__MODULES_DEFAULT_TITLE (#${i})"
        fi

        /usr/bin/env bash "$module" \
            1> "$PLAN__PATH_FIFO_OUT" \
            2> "$PLAN__PATH_FIFO_ERR" &

        Plan::monitor.run "$!" "$PLAN__PATH_LOG_OUT"
        exit_code="$?"

        if ! Plan::utils.ok -i "$PLAN__IGNORE_CODES" "$exit_code"; then
            printf '%b%s %b%s\033[0m\n' \
                "$PLAN__COLOR_STEP_FAIL" "$PLAN__ICON_STEP_FAIL" \
                "$PLAN__COLOR_STEP_TITLE" "$PLAN__MODULE_TITLE"
            exit "$exit_code"
        fi

        printf '%b%s %b%s\033[0m\n' \
            "$PLAN__COLOR_STEP_OK" "$PLAN__ICON_STEP_OK" \
            "$PLAN__COLOR_STEP_TITLE" "$PLAN__MODULE_TITLE"
    ) || exit "$?"
done

exit 0
