# Colors
# ------------------------------------------------
PLAN__COLOR_SPINNER='\033[38;5;75m'
PLAN__COLOR_STEP_TITLE='\033[38;5;99m'
PLAN__COLOR_STEP_LAST='\033[0m'
PLAN__COLOR_STEP_FAIL='\033[31m'
PLAN__COLOR_STEP_OK='\033[32m'

# Icons
# ------------------------------------------------
PLAN__ICON_SPINNER='⡏ ⡏ ⠟ ⠟ ⠻ ⠻ ⢹ ⢹ ⣸ ⣸ ⣴ ⣴ ⣦ ⣦ ⣇ ⣇'
PLAN__ICON_STEP_FAIL='✖'
PLAN__ICON_STEP_OK='✔'
PLAN__ICON_HR='─'

# Logging
# ------------------------------------------------
PLAN__LOGGING_LOGS_DIR=''
PLAN__LOGGING_GET_LAST='true'
PLAN__LOGGING_KEEP_LOGS='false'
