# Colors
# ------------------------------------------------
PLAN__COLOR_SPINNER='\033[38;5;75m'
PLAN__COLOR_STEP_TITLE='\033[38;5;99m'
PLAN__COLOR_STEP_LAST='\033[0m'
PLAN__COLOR_STEP_FAIL='\033[31m'
PLAN__COLOR_STEP_OK='\033[32m'
PLAN__COLORS_LOG_ERROR='\033[31m'
PLAN__COLORS_LOG_WARN='\033[33m'
PLAN__COLORS_LOG_INFO='\033[34m'
PLAN__COLORS_LOG_DEBUG='\033[37m'

# Icons
# ------------------------------------------------
PLAN__ICON_SPINNER='⡏ ⡏ ⠟ ⠟ ⠻ ⠻ ⢹ ⢹ ⣸ ⣸ ⣴ ⣴ ⣦ ⣦ ⣇ ⣇'
PLAN__ICON_STEP_FAIL='✖'
PLAN__ICON_STEP_OK='✔'
PLAN__ICON_HR='─'
PLAN__ICONS_LOG_ERROR=''
PLAN__ICONS_LOG_WARN=''
PLAN__ICONS_LOG_INFO=''
PLAN__ICONS_LOG_DEBUG=''

# Logging
# ------------------------------------------------
PLAN__LOGGING_LOGS_DIR=''
PLAN__LOGGING_GET_LAST='true'
PLAN__LOGGING_KEEP_LOGS='false'
PLAN__LOGGING_LEVEL='INFO'
PLAN__LOGGING_CALLER_LEVEL='ERROR'

# Modules
# ------------------------------------------------
PLAN__MODULES_DEFAULT_TITLE='Running Module'

# State
# ------------------------------------------------
PLAN__STATE_TRACK='true'
PLAN__STATE_ID=''
PLAN__STATE_HASH_ID='true'
PLAN__STATE_DIR="${TEMPDIR:-/tmp}"




