# General
# ------------------------------------------------
PLAN__TERM_TIMEOUT='10'

# Colors
# ------------------------------------------------
PLAN__COLOR_SPINNER='\033[38;5;75m'
PLAN__COLOR_STEP_TITLE='\033[38;5;98m'
PLAN__COLOR_STEP_LAST='\033[0m'
PLAN__COLOR_STEP_FAIL='\033[31m'
PLAN__COLOR_STEP_OK='\033[32m'
PLAN__COLOR_DIR='\033[1;34m'
PLAN__COLOR_DIR_TITLE='\033[34m'
PLAN__COLORS_LOG_ERROR='\033[31m'
PLAN__COLORS_LOG_WARN='\033[33m'
PLAN__COLORS_LOG_INFO='\033[34m'
PLAN__COLORS_LOG_DEBUG='\033[37m'
PLAN__COLOR_STATLOG_INDEX_L='\033[35m'
PLAN__COLOR_STATLOG_INDEX_R='\033[35m'
PLAN__COLOR_STATLOG_INDEX_BRACKET='\033[35m'
PLAN__COLOR_STATLOG_INDEX_DIVIDER='\033[35m'

# Icons
# ------------------------------------------------
PLAN__ICON_SPINNER='⡏ ⡏ ⠟ ⠟ ⠻ ⠻ ⢹ ⢹ ⣸ ⣸ ⣴ ⣴ ⣦ ⣦ ⣇ ⣇'
PLAN__ICON_STEP_FAIL='✖'
PLAN__ICON_STEP_OK='✔'
PLAN__ICON_DIR=''
PLAN__ICON_HR='─'
PLAN__ICONS_LOG_ERROR=''
PLAN__ICONS_LOG_WARN=''
PLAN__ICONS_LOG_INFO=''
PLAN__ICONS_LOG_DEBUG=''

# Logging
# ------------------------------------------------
PLAN__LOGGING_LOGS_DIR=''
PLAN__LOGGING_KEEP_LOGS='false'
PLAN__LOGGING_LEVEL='INFO'
PLAN__LOGGING_CALLER_LEVEL='ERROR'

# Statlog
# ------------------------------------------------
PLAN__STATLOG_GET_LAST='true'
PLAN__STATLOG_TAB_LEN='1'
PLAN__STATLOG_SHOW_DIR='true'
PLAN__STATLOG_SHOW_INDEX='true'
PLAN__STATLOG_STICKY_INDEX='true'
#PLAN__STATLOG_INDEX_POSITION='3'
PLAN__STATLOG_INDEX_BRACKET_L='('
PLAN__STATLOG_INDEX_BRACKET_R=')'
PLAN__STATLOG_INDEX_DIVIDER='/'

# Modules
# ------------------------------------------------
PLAN__MODULES_DEFAULT_TITLE='Running Module'
PLAN__MODULES_ENFORCE_TITLE='false'
PLAN__MODULES_DEFAULT_CMD=''

# State
# ------------------------------------------------
PLAN__STATE_TRACK='true'
PLAN__STATE_ID=''
PLAN__STATE_HASH_ID='true'
PLAN__STATE_DIR="${TEMPDIR:-/tmp}"




